### ISSUE TITLE
1.22.7, 1.23.0, and 1.23.1 Go releases

### ISSUE THREAD

**Issue by dustinmm80** [golang-fips/go#227]
Opening this issue to track tagging releases for 1.22.7, 1.23.0, and 1.23.1 Go releases.

Last time this was done, https://github.com/golang-fips/go/issues/212.

**Comment by pmalhaire** [comment]
I did a wip for go1.23 https://github.com/golang-fips/go/issues/224 if it can help

**Comment by WarheadsSE** [comment]
👋 A nudge to maintainers, this series of updates includes important updates. How can we assist in driving these forward?

cc @ash2k @dustinmm80 @ashmckenzie: We do have 1.22.7 now 👍 (https://github.com/golang-fips/go/tree/go1.22.7-1-openssl-fips)

**Comment by derekparker** [comment]
Sorry for the delay in responding to this issue. The main branch is currently at 1.22.7, and the PR for 1.23.1 is here: https://github.com/golang-fips/go/pull/238.

**Comment by pw20** [comment]
Hi @derekparker,
I tried to build your PR in ubuntu 20.04 fips and scripts/crypto-test.sh failed at
=== RUN   TestBoringServerCurves/curve=25497
=== RUN   TestBoringServerCurves/curve=25497/fipstls

panic: runtime error: index out of range [0] with length 0

goroutine 131 [running]:
crypto/tls.(*Conn).makeClientHello(0xc000398a88)
        /build/golang-fips/go/src/crypto/tls/handshake_client.go:152 +0x18f9
crypto/tls.(*Conn).clientHandshake(0xc000398a88, {0x89fe98, 0xc000132d70})
        /build/golang-fips/go/src/crypto/tls/handshake_client.go:264 +0x7d
crypto/tls.(*Conn).handshakeContext(0xc000398a88, {0x89fca0, 0xb10400})
        /build/golang-fips/go/src/crypto/tls/conn.go:1568 +0x3a6
crypto/tls.(*Conn).HandshakeContext(...)
        /build/golang-fips/go/src/crypto/tls/conn.go:1508
crypto/tls.(*Conn).Handshake(...)
        /build/golang-fips/go/src/crypto/tls/conn.go:1492
crypto/tls.testHandshake.func1()
        /build/golang-fips/go/src/crypto/tls/handshake_test.go:479 +0x145
created by crypto/tls.testHandshake in goroutine 130
        /build/golang-fips/go/src/crypto/tls/handshake_test.go:477 +0x167

Same environment 1.22.x can pass the test.  Do you see similar issue?
Thanks

**Comment by pw20** [comment]
Hi, @derekparker  
Latest commit working now, thanks.

**Comment by dustinmm80** [comment]
All set here, closing issue. Thank you!
